#!/usr/bin/env bash
# generate-worktreeinclude.sh - Auto-generate .worktreeinclude from detected .env* files
#
# Scans the repository for .env* files and generates a .worktreeinclude file
# containing glob patterns so that `git worktree add` (via Claude Code) copies
# env files into new worktrees automatically.
#
# Usage:
#   generate-worktreeinclude.sh [--repo-root <path>] [--force] [--dry-run]
#
# Options:
#   --repo-root <path>  Repository root (default: git rev-parse --show-toplevel)
#   --force             Overwrite existing .worktreeinclude
#   --dry-run           Print what would be written without writing
#
# Output: JSON with generation results

set -euo pipefail

# Defaults
REPO_ROOT=""
FORCE=false
DRY_RUN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --repo-root) REPO_ROOT="$2"; shift 2 ;;
        --force) FORCE=true; shift ;;
        --dry-run) DRY_RUN=true; shift ;;
        -h|--help)
            echo "Usage: generate-worktreeinclude.sh [--repo-root <path>] [--force] [--dry-run]"
            exit 0
            ;;
        *)
            echo "Error: Unknown option $1" >&2
            exit 1
            ;;
    esac
done

# Auto-detect repo root
if [[ -z "$REPO_ROOT" ]]; then
    REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
    if [[ -z "$REPO_ROOT" ]]; then
        echo "Error: Not in a git repository and --repo-root not specified" >&2
        exit 1
    fi
fi

WORKTREEINCLUDE="$REPO_ROOT/.worktreeinclude"

# Check if .worktreeinclude already exists
if [[ -f "$WORKTREEINCLUDE" ]] && [[ "$FORCE" != true ]]; then
    # Already exists, nothing to do
    jq -n \
        --arg status "skipped" \
        --arg reason "already_exists" \
        --arg path "$WORKTREEINCLUDE" \
        '{status: $status, reason: $reason, path: $path}'
    exit 0
fi

# Collect .env* files from repository
# -L: follow symlinks (monorepo workspace support)
# Exclude: node_modules, .git, *-worktrees
ENV_FILES=()
while IFS= read -r -d '' env_file; do
    ENV_FILES+=("$env_file")
done < <(find -L "$REPO_ROOT" -maxdepth 10 -name ".env*" -type f \
    -not -path "*/node_modules/*" \
    -not -path "*/.git/*" \
    -not -path "*-worktrees/*" \
    -not -name ".envrc" \
    -print0 2>/dev/null)

if [[ ${#ENV_FILES[@]} -eq 0 ]]; then
    jq -n \
        --arg status "skipped" \
        --arg reason "no_env_files" \
        --arg path "$WORKTREEINCLUDE" \
        '{status: $status, reason: $reason, path: $path}'
    exit 0
fi

# Build unique patterns from detected files
# Strategy:
#   - Root-level .env* files → exact filename patterns (e.g., .env, .env.local)
#   - Subdirectory .env* files → glob patterns (e.g., **/.env, **/.env.local)
declare -A ROOT_PATTERNS
declare -A GLOB_PATTERNS

for env_file in "${ENV_FILES[@]}"; do
    relative_path="${env_file#$REPO_ROOT/}"
    filename=$(basename "$env_file")
    dir=$(dirname "$relative_path")

    if [[ "$dir" == "." ]]; then
        ROOT_PATTERNS["$filename"]=1
    else
        GLOB_PATTERNS["**/$filename"]=1
    fi
done

# Generate .worktreeinclude content
CONTENT="# Auto-generated by generate-worktreeinclude.sh
# Patterns for .env* files to be copied into new worktrees
# Regenerate: \$SKILLS_DIR/_lib/scripts/generate-worktreeinclude.sh --force
"

# Sort and write root-level patterns first
PATTERNS=()
for pattern in "${!ROOT_PATTERNS[@]}"; do
    PATTERNS+=("$pattern")
done
# Disable globbing to prevent ** expansion during array assignment
set -f
IFS=$'\n' SORTED_ROOT=($(printf '%s\n' "${PATTERNS[@]}" | sort)); unset IFS
set +f

for pattern in "${SORTED_ROOT[@]}"; do
    CONTENT+="$pattern"$'\n'
done

# Then glob patterns
PATTERNS=()
for pattern in "${!GLOB_PATTERNS[@]}"; do
    PATTERNS+=("$pattern")
done
if [[ ${#PATTERNS[@]} -gt 0 ]]; then
    set -f
    IFS=$'\n' SORTED_GLOB=($(printf '%s\n' "${PATTERNS[@]}" | sort)); unset IFS
    set +f
    for pattern in "${SORTED_GLOB[@]}"; do
        CONTENT+="$pattern"$'\n'
    done
fi

# Collect all patterns for JSON output
ALL_PATTERNS=()
for p in "${SORTED_ROOT[@]}"; do ALL_PATTERNS+=("$p"); done
if [[ ${#PATTERNS[@]} -gt 0 ]]; then
    for p in "${SORTED_GLOB[@]}"; do ALL_PATTERNS+=("$p"); done
fi

if [[ "$DRY_RUN" == true ]]; then
    # Output what would be written
    PATTERNS_JSON=$(printf '%s\n' "${ALL_PATTERNS[@]}" | jq -R . | jq -sc .)
    jq -n \
        --arg status "dry_run" \
        --arg path "$WORKTREEINCLUDE" \
        --arg content "$CONTENT" \
        --argjson patterns "$PATTERNS_JSON" \
        --argjson env_count "${#ENV_FILES[@]}" \
        '{status: $status, path: $path, content: $content, patterns: $patterns, env_files_detected: $env_count}'
    exit 0
fi

# Write the file
printf '%s' "$CONTENT" > "$WORKTREEINCLUDE"

PATTERNS_JSON=$(printf '%s\n' "${ALL_PATTERNS[@]}" | jq -R . | jq -sc .)
jq -n \
    --arg status "generated" \
    --arg path "$WORKTREEINCLUDE" \
    --argjson patterns "$PATTERNS_JSON" \
    --argjson env_count "${#ENV_FILES[@]}" \
    '{status: $status, path: $path, patterns: $patterns, env_files_detected: $env_count}'
